version: "3.8"

services:
  db:
    image: postgres:11-alpine
    container_name: etl_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./queries:/queries

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgres://myuser:example@db:5432/mydb"
    depends_on:
      - db
    volumes:
      - .:/app:cached
    working_dir: /app
    command: python src/load_data.py

volumes:
  postgres_data:
